blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/dzigor92/pogo-code-redemption/security/advisories/new
    about: Please report security vulnerabilities privately.
